### ISSUE TITLE
In the compute env, zones don't take precedence over regions?

### ISSUE THREAD

**Issue by phiweger** [seqeralabs/nf-tower#294]
Zones were introduced in #288 and when creating a compute env on tower it states that when zones are declared (additionally to region, which one has to set) then the zones take precedence.

However, this does not seem to be the case in a failed run of mine (run ID 1wjMVNJazkr1YO):

<img width="1044" alt="Screenshot 2021-03-27 at 2 54 38 AM" src="https://user-images.githubusercontent.com/3918306/112706980-3a60bb80-8ea8-11eb-8263-cf3bfee73246.png">

<img width="1028" alt="Screenshot 2021-03-27 at 2 55 12 AM" src="https://user-images.githubusercontent.com/3918306/112706982-3e8cd900-8ea8-11eb-9a9b-6f837072aef3.png">

Is this a bug? Ie shouldn't it complain that the quota of europe-west3-__c__ is too low?

**Comment by pditommaso** [comment]
Thanks for reporting, checking.

**Comment by jordeu** [comment]
@phiweger can you check the google cloud console when you run a job?
![Screenshot from 2021-03-30 09-54-15](https://user-images.githubusercontent.com/1315429/112953678-f8e93e00-913d-11eb-9fa7-206f2e2b374a.png)

Everything seems fine at Tower and Nextflow side. And this error message that you get comes directly from the google platform, so I'm not sure why they mention the region instead of the zone.

**Comment by pditommaso** [comment]
Closing this, since it's fine on our side. Feel free to comment/re-open if needed.
